import type { DataDetail } from "../types/flow";

export const dataCatalog: DataDetail[] = [
  {
    id: "data-script-source",
    title: "脚本源码",
    category: "artifact",
    producer: "ScriptsView / AI 生成接口",
    consumer: "脚本保存 API / 动态 Runner",
    transformation:
      "CodeMirror 编辑；可由 JSDoc 派生参数；执行前剥离 import/type/default wrapper 并转译。",
    lifecycle: "保存后长期存在 scripts/*.{mjs,js}；删除主文件不会自动清除所有关联产物。",
    purpose: "定义一次浏览器自动化要执行的逻辑和可配置参数。",
    fields: [
      {
        path: "filename",
        type: "string",
        requirement: "required",
        example: "04_youtube_feed.mjs",
        purpose: "定位磁盘脚本，并关联 history、pinned tab 与 trace。",
      },
      {
        path: "content",
        type: "string",
        requirement: "required",
        example: "export default async function run({ page, log, db, params }) { … }",
        purpose: "保存并最终转译执行的源码正文。",
      },
      {
        path: "JSDoc params[]",
        type: "ScriptParamField[]",
        requirement: "optional",
        example: "[{ name: 'limit', type: 'number', default: 20, label: '采集数量' }]",
        purpose: "从注释生成运行前参数控件，不参与稳定脚本身份。",
      },
    ],
    sourceIds: ["src-scripts-view", "src-editor", "src-params", "src-server-scripts"],
  },
  {
    id: "data-validation-result",
    title: "语法校验结果",
    category: "event",
    producer: "服务端脚本校验接口",
    consumer: "ScriptsView / ValidationBanner",
    transformation: "源码经校验后归一为 valid、message 和可选错误位置。",
    lifecycle: "仅存在于编辑会话；不会作为执行准入记录持久化。",
    purpose: "在保存或运行前向作者暴露可定位的语法问题。",
    fields: [
      {
        path: "valid",
        type: "boolean",
        requirement: "required",
        example: "false",
        purpose: "表示当前源码是否通过校验。",
      },
      {
        path: "errors[].line",
        type: "number",
        requirement: "conditional",
        example: "18",
        purpose: "将问题定位到编辑器行。",
      },
      {
        path: "errors[].message",
        type: "string",
        requirement: "conditional",
        example: "Unexpected token",
        purpose: "解释为什么源码不能被安全转译。",
      },
    ],
    sourceIds: ["src-scripts-view", "src-automation-types", "src-server-scripts"],
  },
  {
    id: "data-history-snapshot",
    title: "历史快照",
    category: "artifact",
    producer: "脚本保存 API",
    consumer: "HistoryTraceDrawer / 历史恢复接口",
    transformation: "安全化脚本名后，以 epoch 生成源码和元数据文件。",
    lifecycle: "长期存在 .history/<safeName>/<epoch>.{mjs,json}；写入不是原子事务。",
    purpose: "保留可回看的脚本版本，降低编辑覆盖带来的损失。",
    fields: [
      {
        path: "historyId",
        type: "string",
        requirement: "required",
        example: "1760000000000",
        purpose: "关联同一次快照的源码与元数据。",
      },
      {
        path: "content",
        type: "string",
        requirement: "required",
        example: "// snapshot source …",
        purpose: "恢复时重新载入的脚本版本。",
      },
      {
        path: "timestamp",
        type: "string",
        requirement: "required",
        example: "2026/8/12 10:30:00",
        purpose: "向用户说明快照创建时间；当前为 locale string。",
      },
    ],
    sourceIds: ["src-server-scripts", "src-scripts-view"],
  },
  {
    id: "data-tab-descriptor",
    title: "Chrome Tab 描述",
    category: "state",
    producer: "Stagehand context.pages()",
    consumer: "TabsView / 脚本执行路由",
    transformation: "pages 数组按当前位置映射为 index、title、url 和 favicon。",
    lifecycle: "瞬时快照；页面打开、关闭或重排后 index 可能改变。",
    purpose: "让用户选择脚本应在哪个浏览器页面上运行。",
    fields: [
      {
        path: "index",
        type: "number",
        requirement: "required",
        example: "2",
        purpose: "当前 pages 数组中的位置，不是稳定 Page ID。",
      },
      {
        path: "title",
        type: "string",
        requirement: "required",
        example: "Example feed",
        purpose: "帮助用户识别页面。",
      },
      {
        path: "url",
        type: "string",
        requirement: "required",
        example: "https://example.com/feed",
        purpose: "用于展示、Pinned 匹配和执行前 URL 校准。",
      },
      {
        path: "favicon",
        type: "string",
        requirement: "required",
        example: "https://example.com/favicon.ico",
        purpose: "提供标签视觉识别；不可作为身份键。",
      },
    ],
    sourceIds: ["src-tabs-view", "src-server-tabs", "src-automation-types"],
  },
  {
    id: "data-pinned-tab",
    title: "Pinned Tab 配置",
    category: "artifact",
    producer: "Pinned Tabs UI",
    consumer: "TabsView / 执行前 URL 校准",
    transformation: "配置 URL 与实时 tabs 比较，派生 closed、domain 或 exact 状态。",
    lifecycle: "长期存在 scripts/.local/pinned_tabs.json；保存失败目前可能被吞掉。",
    purpose: "记录常用目标页及其默认脚本，并在页面缺失时恢复目标。",
    fields: [
      {
        path: "id",
        type: "string",
        requirement: "required",
        example: "feed-monitor",
        purpose: "稳定关联配置项和编辑操作。",
      },
      {
        path: "url",
        type: "string",
        requirement: "required",
        example: "https://example.com/feed",
        purpose: "进行 exact/domain 匹配并在需要时导航。",
      },
      {
        path: "scriptFilename",
        type: "string",
        requirement: "optional",
        example: "04_youtube_feed.mjs",
        purpose: "将常驻页面和默认自动化脚本关联。",
      },
      {
        path: "derivedStatus",
        type: "'closed' | 'domain' | 'exact'",
        requirement: "conditional",
        example: "domain",
        purpose: "说明当前浏览器是否已有可复用的目标页面。",
      },
    ],
    sourceIds: ["src-tabs-view", "src-pinned", "src-automation-types"],
  },
  {
    id: "data-execution-request",
    title: "执行请求",
    category: "request",
    producer: "ScriptsView / TabsView",
    consumer: "GET /api/scripts/execute/stream",
    transformation: "对象被编码为 EventSource query；params 以 JSON 文本传输。",
    lifecycle: "单次 SSE 连接；断线后不会自动恢复或补发事件。",
    purpose: "绑定要运行的脚本、目标页面、参数和可选调用方 runId。",
    fields: [
      {
        path: "filename",
        type: "string",
        requirement: "required",
        example: "04_youtube_feed.mjs",
        purpose: "选择服务端要读取和执行的脚本文件。",
      },
      {
        path: "tabIndex",
        type: "string(number)",
        requirement: "optional",
        example: "2",
        purpose: "选择当前 Stagehand pages 数组中的目标位置，省略时回退到 0。",
      },
      {
        path: "targetUrl",
        type: "string",
        requirement: "optional",
        example: "https://example.com/feed",
        purpose: "执行前验证并必要时纠正目标页面 URL。",
      },
      {
        path: "params",
        type: "JSON string",
        requirement: "optional",
        example: '{"limit":20,"saveToDb":true}',
        purpose: "为 JSDoc 参数化脚本提供本次运行值；无效 JSON 当前降级为 {}。",
      },
      {
        path: "runId",
        type: "string",
        requirement: "optional",
        example: "run_1760000000000_550e8400-e29b-41d4-a716-446655440000",
        purpose: "关联取消、SSE 和 Trace；必须符合 1–100 位字母数字、下划线或连字符。",
      },
    ],
    sourceIds: ["src-scripts-view", "src-tabs-view", "src-execution"],
  },
  {
    id: "data-run-control",
    title: "运行控制状态",
    category: "state",
    producer: "执行路由",
    consumer: "断线处理 / cancel API / Runner",
    transformation: "runId 注册到 activeScriptExecutions，并关联一个 AbortController。",
    lifecycle: "仅存在于 Fastify 进程内；终止后删除，服务重启无法恢复。",
    purpose: "避免重复 runId，并为协作式取消提供共享信号。",
    fields: [
      {
        path: "runId",
        type: "string",
        requirement: "required",
        example: "run_1760000000000_…",
        purpose: "本次运行在控制表、SSE 和 Trace 中的关联键。",
      },
      {
        path: "controller",
        type: "AbortController",
        requirement: "required",
        example: "AbortController { signal.aborted: false }",
        purpose: "向可中止页面操作和 fetch 广播取消。",
      },
      {
        path: "executionFinished",
        type: "boolean",
        requirement: "required",
        example: "false",
        purpose: "区分正常收尾与客户端提前断线。",
      },
    ],
    sourceIds: ["src-execution", "src-cancel"],
  },
  {
    id: "data-runtime-context",
    title: "动态脚本运行上下文",
    category: "state",
    producer: "Fastify Runner",
    consumer: "用户脚本 AsyncFunction",
    transformation: "页面和 fetch 被包装为可观察 AbortSignal 的代理，其他能力直接注入。",
    lifecycle: "只在一次 AsyncFunction 调用期间存在，但与 Fastify 共享进程和事件循环。",
    purpose: "向用户脚本提供浏览器、日志、数据库、参数、取消和网络能力。",
    fields: [
      {
        path: "page",
        type: "Stagehand Page proxy",
        requirement: "required",
        example: "page",
        purpose: "执行导航、点击、提取和截图等页面操作。",
      },
      {
        path: "db",
        type: "Database helper",
        requirement: "required",
        example: "db.upsert('videos', row)",
        purpose: "允许脚本把采集结果持久化到本地 SQLite。",
      },
      {
        path: "params",
        type: "Record<string, unknown>",
        requirement: "required",
        example: "{ limit: 20 }",
        purpose: "向脚本传入本次执行配置。",
      },
      {
        path: "signal",
        type: "AbortSignal",
        requirement: "required",
        example: "AbortSignal { aborted: false }",
        purpose: "支持脚本和代理在取消后尽快停止。",
      },
      {
        path: "fetch",
        type: "abortable fetch",
        requirement: "required",
        example: "fetch('/api/items')",
        purpose: "执行网络请求并自动合并运行取消信号。",
      },
    ],
    sourceIds: ["src-execution", "src-db-helper", "src-cancel"],
  },
  {
    id: "data-sse-event",
    title: "SSE 执行事件",
    category: "event",
    producer: "sendEvent / sendLog",
    consumer: "ScriptsView / TabsView",
    transformation: "对象序列化为默认 message 事件的 data 行；没有 event id 或 retry。",
    lifecycle: "实时事件仅随连接存在；其中 log/frame/cancelled 的部分信息会进入 Trace。",
    purpose: "让 UI 同步展示运行进度、截图、成功、失败或取消。",
    fields: [
      {
        path: "type",
        type: "'log' | 'frame' | 'done' | 'error' | 'cancelled' | string",
        requirement: "required",
        example: "frame",
        purpose: "区分日志、帧和终态；string fallback 保留 sendLog 自定义类型。",
      },
      {
        path: "runId",
        type: "string",
        requirement: "conditional",
        example: "run_1760000000000_…",
        purpose: "关联本次事件与运行；早期致命错误可能缺失。",
      },
      {
        path: "time",
        type: "locale time string",
        requirement: "conditional",
        example: "10:30:08",
        purpose: "向用户展示事件发生时间；不适合作为跨 locale 排序键。",
      },
      {
        path: "message",
        type: "string",
        requirement: "required",
        example: "已提取第 20 条记录",
        purpose: "用自然语言解释当前动作或失败原因。",
      },
      {
        path: "frameUrl",
        type: "string",
        requirement: "conditional",
        example: "http://localhost:3001/api/traces/run_…/frame/frame_3.jpg",
        purpose: "仅 frame 事件提供，对应当前或复用的最近截图。",
      },
    ],
    sourceIds: ["src-execution", "src-trace", "src-automation-types"],
  },
  {
    id: "data-trace-artifact",
    title: "Trace 运行产物",
    category: "artifact",
    producer: "sendLog",
    consumer: "Trace API / HistoryTraceDrawer",
    transformation: "日志追加到 traceLogs，截图按条件写为 JPEG，再重写 trace.json 汇总。",
    lifecycle: "长期存在 traces/<runId>/；可能在异常退出时只保留部分文件。",
    purpose: "回看一次自动化运行发生了什么，并把文字步骤与页面截图关联。",
    fields: [
      {
        path: "runId",
        type: "string",
        requirement: "required",
        example: "run_1760000000000_…",
        purpose: "Trace 目录和 API 查询的稳定关联键。",
      },
      {
        path: "timestamp",
        type: "locale datetime string",
        requirement: "required",
        example: "2026/8/12 10:30:08",
        purpose: "当前代表最后写入时间，不是固定开始时间。",
      },
      {
        path: "frames[]",
        type: "{ step, time, message, frameUrl }[]",
        requirement: "required",
        example: "[{ step: 3, time: '10:30:08', message: '滚动页面', frameUrl: '…' }]",
        purpose: "将可视步骤与截图引用关联；多个 frame 可复用同一图片。",
      },
      {
        path: "logs[]",
        type: "{ time, message, type }[]",
        requirement: "required",
        example: "[{ time: '10:30:08', message: '保存完成', type: 'log' }]",
        purpose: "记录经 sendLog 发送的文本事件；done/error 通常不在其中。",
      },
      {
        path: "totalFrames / totalLogs",
        type: "number",
        requirement: "required",
        example: "12 / 18",
        purpose: "为历史列表提供无需展开详情的数量摘要。",
      },
    ],
    sourceIds: ["src-trace", "src-execution", "src-automation-types"],
  },
  {
    id: "data-db-operation",
    title: "数据库操作",
    category: "request",
    producer: "用户脚本 / DatabaseView",
    consumer: "db helper / Fastify DB routes",
    transformation: "值可参数绑定，但部分 API 将表名或列名直接拼入 SQL。",
    lifecycle: "请求短暂存在；成功后数据长期写入 data/cbg_data.db。",
    purpose: "创建动态采集表、查询分页数据、清空表或删除目标行。",
    fields: [
      {
        path: "table",
        type: "string",
        requirement: "required",
        example: "youtube_videos",
        purpose: "选择操作目标；作为 SQL identifier 时必须由 schema 白名单验证。",
      },
      {
        path: "columns[]",
        type: "string[]",
        requirement: "conditional",
        example: "['video_id', 'title']",
        purpose: "选择或生成列；不能只依赖普通值参数绑定保护。",
      },
      {
        path: "values",
        type: "Record<string, unknown>",
        requirement: "conditional",
        example: "{ video_id: 'abc123', title: '示例标题' }",
        purpose: "提供写入值或删除条件值。",
      },
      {
        path: "page / pageSize",
        type: "number",
        requirement: "conditional",
        example: "1 / 50",
        purpose: "限制 DatabaseView 一次读取的数据窗口。",
      },
    ],
    sourceIds: ["src-db-routes", "src-db-helper", "src-db-view"],
  },
  {
    id: "data-db-result",
    title: "SQLite 行集与副作用",
    category: "side-effect",
    producer: "SQLite / db helper",
    consumer: "用户脚本 / DatabaseView",
    transformation: "查询结果转为对象数组；upsert 当前实际执行 INSERT OR REPLACE。",
    lifecycle: "行数据持久存在，直到脚本覆盖、删除行、清表或移除数据库。",
    purpose: "保存采集结果并提供浏览、分页和导出能力。",
    fields: [
      {
        path: "rows[]",
        type: "Record<string, unknown>[]",
        requirement: "required",
        example: "[{ video_id: 'abc123', title: '示例标题' }]",
        purpose: "表示当前查询页或脚本读取到的数据。",
      },
      {
        path: "total",
        type: "number",
        requirement: "conditional",
        example: "248",
        purpose: "支持分页指标和总量展示。",
      },
      {
        path: "primary key candidate",
        type: "string",
        requirement: "conditional",
        example: "video_id",
        purpose: "当前前端推测删除键；可能不是真实或完整主键。",
      },
      {
        path: "exportedRows",
        type: "Record<string, unknown>[]",
        requirement: "conditional",
        example: "当前已加载页的 50 行",
        purpose: "生成导出文件；当前并不代表整张表。",
      },
    ],
    sourceIds: ["src-db-view", "src-db-helper", "src-db-routes", "src-youtube-script"],
  },
];
