import type { FlowDefinition } from "../types/flow";

export const flows: FlowDefinition[] = [
  {
    id: "flow-scripts",
    number: "01",
    title: "脚本管理",
    summary: "从磁盘发现脚本，经编辑、参数解析、校验和历史快照，形成可执行版本。",
    outcome: "主路径终点是磁盘上的可执行脚本；AI、返工、保存失败和删除是有源码依据的变体。",
    accent: "#eeb85f",
    primaryStageIds: [
      "scripts-discovered",
      "scripts-loaded",
      "scripts-edited",
      "scripts-validated",
      "scripts-saved",
      "scripts-ready",
    ],
    primaryTransitionIds: [
      "scripts-list",
      "scripts-select",
      "scripts-edit",
      "scripts-validate",
      "scripts-save",
      "scripts-handoff",
    ],
    stages: [
      {
        id: "scripts-discovered",
        eyebrow: "INPUT",
        title: "发现脚本",
        state: "文件列表已返回",
        progress: 0,
        participants: ["Vue SPA", "Fastify", "Script FS"],
        before: "UI 尚不知道 scripts 目录中有哪些可用脚本。",
        after: "侧边栏拥有可选择的 .mjs/.js 文件名。",
        explanation: "先以磁盘为事实源建立清单，避免编辑器展示不存在或过期的脚本身份。",
        outputs: ["脚本文件名列表"],
        sourceIds: ["src-scripts-view", "src-server-scripts"],
      },
      {
        id: "scripts-loaded",
        eyebrow: "READ",
        title: "载入源码",
        state: "当前脚本进入编辑会话",
        progress: 0.18,
        participants: ["ScriptsView", "Script FS"],
        before: "只有脚本文件名，没有可编辑内容。",
        after: "源码、文件名和派生参数进入前端状态。",
        explanation: "选择时读取完整源码，并让 JSDoc 参数定义与当前版本保持一致。",
        outputs: ["源码正文", "当前文件名", "JSDoc 参数字段"],
        sourceIds: ["src-scripts-view", "src-params", "src-server-scripts"],
      },
      {
        id: "scripts-edited",
        eyebrow: "AUTHOR",
        title: "编辑或生成",
        state: "内存草稿发生变化",
        progress: 0.38,
        participants: ["用户", "CodeMirror", "AI 服务（可选）"],
        before: "编辑器内容与磁盘版本相同。",
        after: "得到尚未证明可执行的候选源码。",
        explanation:
          "作者可以直接修改，也可让 AI 生成候选代码；两者都只是草稿，不能冒充已验证版本。",
        outputs: ["候选源码", "更新后的参数定义"],
        sourceIds: ["src-editor", "src-scripts-view", "src-ai", "src-params"],
      },
      {
        id: "scripts-validated",
        eyebrow: "CHECK",
        title: "语法校验",
        state: "收到 valid/errors 结果",
        progress: 0.57,
        participants: ["ScriptsView", "Fastify transpiler"],
        before: "候选源码可能包含语法或转译错误。",
        after: "UI 知道源码是否通过当前校验及错误位置。",
        explanation: "在写入和运行前尽早暴露可定位问题，但当前结果不是沙箱安全证明。",
        outputs: ["ValidationResult", "错误行列（若失败）"],
        sourceIds: ["src-scripts-view", "src-server-scripts", "src-automation-types"],
      },
      {
        id: "scripts-saved",
        eyebrow: "DURABLE",
        title: "保存与快照",
        state: "主文件和历史文件写入",
        progress: 0.78,
        participants: ["Fastify", "Script FS", "History FS"],
        before: "最新草稿仅存在浏览器内存。",
        after: "主脚本可被 Runner 读取，并尝试产生历史快照。",
        explanation: "持久化让执行读取确定的磁盘版本，快照则提供人工恢复点；两次写入目前不是事务。",
        outputs: ["scripts/<filename>", ".history/<safeName>/<epoch>.mjs", "历史元数据"],
        sourceIds: ["src-scripts-view", "src-server-scripts"],
      },
      {
        id: "scripts-ready",
        eyebrow: "HANDOFF",
        title: "进入可执行态",
        state: "脚本可交给执行流",
        progress: 1,
        participants: ["ScriptsView", "TabsView", "Execution API"],
        before: "脚本已有磁盘版本，但尚未绑定本次运行参数和目标 tab。",
        after: "执行流可以组装 filename、tabIndex、targetUrl 与 params。",
        explanation: "脚本管理在这里结束；真正的浏览器副作用属于独立执行流。",
        outputs: ["可执行脚本标识", "参数 schema"],
        sourceIds: ["src-scripts-view", "src-tabs-view", "src-execution"],
      },
    ],
    transitions: [
      {
        id: "scripts-list",
        from: "scripts-discovered",
        to: "scripts-discovered",
        label: "读取脚本目录",
        kind: "normal",
        timing: "进入 Scripts 页面时",
        window: [0, 0.08],
        explanation: "前端请求脚本列表，服务端只返回受支持扩展名，让后续选择拥有明确身份。",
        payloadExample: '{ "files": ["03_custom_playwright.mjs", "04_youtube_feed.mjs"] }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-scripts-view", "src-server-scripts"],
      },
      {
        id: "scripts-select",
        from: "scripts-discovered",
        to: "scripts-loaded",
        label: "选择并读取",
        kind: "normal",
        timing: "用户选择文件后",
        window: [0.08, 0.22],
        explanation: "文件名换取完整源码，随后从同一内容解析参数，防止参数表单与编辑器脱节。",
        payloadExample: '{ "filename": "04_youtube_feed.mjs", "content": "export default async…" }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-scripts-view", "src-params", "src-server-scripts"],
      },
      {
        id: "scripts-edit",
        from: "scripts-loaded",
        to: "scripts-edited",
        label: "更新草稿",
        kind: "normal",
        timing: "编辑器输入期间",
        window: [0.22, 0.42],
        explanation: "CodeMirror 将变更同步给父视图；此时只更新内存，不产生磁盘副作用。",
        payloadExample: '{ "content": "await page.goto(params.url)" }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-editor", "src-scripts-view"],
      },
      {
        id: "scripts-ai-generate",
        from: "scripts-loaded",
        to: "scripts-edited",
        label: "AI 生成候选",
        kind: "alternate",
        timing: "用户提交生成提示后",
        window: [0.24, 0.42],
        explanation:
          "外部模型返回候选源码，再进入与人工编辑相同的校验和保存路径；它不是可信运行结果。",
        payloadExample:
          '{ "prompt": "提取当前页面的文章标题", "generatedCode": "export default async…" }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-scripts-view", "src-ai"],
      },
      {
        id: "scripts-validate",
        from: "scripts-edited",
        to: "scripts-validated",
        label: "提交语法校验",
        kind: "normal",
        timing: "保存或运行前",
        window: [0.42, 0.61],
        explanation: "候选源码交给服务端解析，返回是否有效和可显示的错误位置。",
        payloadExample: '{ "valid": true, "errors": [] }',
        dataDetailId: "data-validation-result",
        sourceIds: ["src-scripts-view", "src-server-scripts", "src-automation-types"],
      },
      {
        id: "scripts-rework",
        from: "scripts-validated",
        to: "scripts-edited",
        label: "校验失败返工",
        kind: "recovery",
        timing: "valid = false 时",
        window: [0.5, 0.66],
        explanation: "错误被展示后返回编辑阶段；当前 AI 路径并未可靠地把失败作为保存阻断条件。",
        payloadExample:
          '{ "valid": false, "errors": [{ "line": 18, "message": "Unexpected token" }] }',
        dataDetailId: "data-validation-result",
        sourceIds: ["src-scripts-view", "src-automation-types"],
      },
      {
        id: "scripts-save",
        from: "scripts-validated",
        to: "scripts-saved",
        label: "写主文件与快照",
        kind: "normal",
        timing: "校验后保存",
        window: [0.61, 0.82],
        explanation: "服务端覆盖主脚本并尝试创建带 epoch 的历史副本，形成可执行磁盘版本。",
        payloadExample: '{ "filename": "04_youtube_feed.mjs", "historyId": "1760000000000" }',
        dataDetailId: "data-history-snapshot",
        sourceIds: ["src-scripts-view", "src-server-scripts"],
      },
      {
        id: "scripts-save-failed",
        from: "scripts-validated",
        to: "scripts-edited",
        label: "写入失败",
        kind: "failure",
        timing: "文件 I/O 抛错时",
        window: [0.64, 0.8],
        explanation: "主文件或快照失败时应保留草稿并重试；当前部分 history I/O 错误会被吞掉。",
        payloadExample: '{ "error": "Failed to save history snapshot", "draftPreserved": true }',
        dataDetailId: "data-history-snapshot",
        sourceIds: ["src-server-scripts", "src-scripts-view"],
      },
      {
        id: "scripts-handoff",
        from: "scripts-saved",
        to: "scripts-ready",
        label: "交给执行流",
        kind: "normal",
        timing: "用户点击运行后",
        window: [0.82, 1],
        explanation:
          "UI 用已选文件、页面和参数构造 SSE 请求；保存失败时当前实现仍可能运行旧磁盘代码。",
        payloadExample:
          '{ "filename": "04_youtube_feed.mjs", "tabIndex": "2", "params": "{\\"limit\\":20}" }',
        dataDetailId: "data-execution-request",
        sourceIds: ["src-scripts-view", "src-execution"],
      },
      {
        id: "scripts-delete",
        from: "scripts-ready",
        to: "scripts-discovered",
        label: "删除并刷新",
        kind: "alternate",
        timing: "用户确认删除后",
        window: [0.86, 1],
        explanation: "删除主脚本后重新读取列表；history、trace 和 pinned 引用不会自动级联。",
        payloadExample: '{ "filename": "retired-script.mjs", "deleted": true }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-scripts-view", "src-server-scripts", "src-pinned", "src-trace"],
      },
    ],
  },
  {
    id: "flow-tabs",
    number: "02",
    title: "Chrome Tabs",
    summary:
      "通过 Stagehand/CDP 读取外部 Chrome pages，解析 Pinned Tab，并把瞬时 tabIndex 交给执行流。",
    outcome: "得到当前时刻可使用的目标页面；页面身份是位置索引，任何页面变化都要求重新发现。",
    accent: "#68c7bd",
    primaryStageIds: [
      "tabs-requested",
      "tabs-connected",
      "tabs-indexed",
      "tabs-pinned-resolved",
      "tabs-targeted",
      "tabs-ready",
    ],
    primaryTransitionIds: [
      "tabs-connect",
      "tabs-enumerate",
      "tabs-resolve-pinned",
      "tabs-ensure",
      "tabs-handoff",
    ],
    stages: [
      {
        id: "tabs-requested",
        eyebrow: "REQUEST",
        title: "请求页面清单",
        state: "UI 等待实时浏览器状态",
        progress: 0,
        participants: ["TabsView", "Fastify"],
        before: "前端只保留上次渲染的页面快照。",
        after: "服务端开始确认 Stagehand 是否可用。",
        explanation: "每次刷新都重新询问浏览器，避免把旧 UI 状态当作当前页面事实。",
        outputs: ["GET /api/tabs"],
        sourceIds: ["src-tabs-view", "src-server-tabs"],
      },
      {
        id: "tabs-connected",
        eyebrow: "BOUNDARY",
        title: "连接 CDP",
        state: "Stagehand context 可访问",
        progress: 0.2,
        participants: ["Fastify", "Stagehand", "外部 Chrome"],
        before: "服务端尚不能确认 Chrome 调试端点可用。",
        after: "可以读取 context.pages() 或返回连接错误。",
        explanation: "这是 Node 服务与外部浏览器的控制权交接点，连接失败时不能继续伪造页面状态。",
        outputs: ["Stagehand instance", "Browser context"],
        sourceIds: ["src-server-tabs"],
      },
      {
        id: "tabs-indexed",
        eyebrow: "SNAPSHOT",
        title: "枚举并编号",
        state: "pages 映射为 BrowserTab[]",
        progress: 0.4,
        participants: ["Stagehand", "Tabs API", "TabsView"],
        before: "只有 Page 对象集合。",
        after: "UI 拥有 index、title、url 和 favicon。",
        explanation: "位置索引便于展示和调用，但不是稳定浏览器 Page ID，页面重排后必须重新获取。",
        outputs: ["BrowserTab[]"],
        sourceIds: ["src-server-tabs", "src-tabs-view", "src-automation-types"],
      },
      {
        id: "tabs-pinned-resolved",
        eyebrow: "DECISION",
        title: "解析 Pinned 状态",
        state: "closed / domain / exact",
        progress: 0.6,
        participants: ["TabsView", "Pinned JSON", "BrowserTab[]"],
        before: "持久配置尚未与实时页面比较。",
        after: "每个 pinned 配置拥有可解释的匹配状态。",
        explanation: "精确匹配可直接复用，同域匹配可能导航，closed 则需要新建页面。",
        outputs: ["PinnedTabStatus"],
        sourceIds: ["src-tabs-view", "src-pinned", "src-automation-types"],
      },
      {
        id: "tabs-targeted",
        eyebrow: "CONTROL",
        title: "激活或确保页面",
        state: "目标 Page 可用",
        progress: 0.8,
        participants: ["TabsView", "Tabs API", "Chrome"],
        before: "目标可能不存在、仅同域匹配或未处于前台。",
        after: "已有页面被激活，或创建/导航到目标 URL。",
        explanation: "把配置意图落实到实际 Chrome 页面，为运行脚本准备可操作目标。",
        outputs: ["目标 tabIndex", "校准后的 URL"],
        sourceIds: ["src-tabs-view", "src-server-tabs", "src-pinned"],
      },
      {
        id: "tabs-ready",
        eyebrow: "HANDOFF",
        title: "绑定脚本与参数",
        state: "执行请求可构造",
        progress: 1,
        participants: ["TabsView", "Execution API"],
        before: "页面已确定，但尚未产生运行连接。",
        after: "tabIndex、targetUrl、filename 和 params 进入执行流。",
        explanation: "Tabs 流只负责选择页面，不声称脚本已开始或目标索引仍永久有效。",
        outputs: ["ExecutionRequest"],
        sourceIds: ["src-tabs-view", "src-execution"],
      },
    ],
    transitions: [
      {
        id: "tabs-connect",
        from: "tabs-requested",
        to: "tabs-connected",
        label: "确保 Stagehand",
        kind: "normal",
        timing: "GET /api/tabs 处理开始",
        window: [0, 0.22],
        explanation: "服务端复用或初始化 Stagehand，确认 CDP 边界可访问后才读取页面。",
        payloadExample: '{ "cdp": "configured endpoint", "connected": true }',
        dataDetailId: "data-tab-descriptor",
        sourceIds: ["src-server-tabs"],
      },
      {
        id: "tabs-cdp-failed",
        from: "tabs-requested",
        to: "tabs-requested",
        label: "CDP 不可达",
        kind: "failure",
        timing: "Stagehand 初始化或复用失败",
        window: [0.06, 0.2],
        explanation: "流程停止并暴露错误；恢复依赖启动或修复外部 Chrome 后再次刷新。",
        payloadExample: '{ "error": "Stagehand 未连接到 Chrome 浏览器。" }',
        dataDetailId: "data-tab-descriptor",
        sourceIds: ["src-server-tabs", "src-tabs-view"],
      },
      {
        id: "tabs-enumerate",
        from: "tabs-connected",
        to: "tabs-indexed",
        label: "pages → tabs",
        kind: "normal",
        timing: "连接成功后立即",
        window: [0.22, 0.42],
        explanation:
          "context.pages() 的当前位置成为 index，并读取标题、URL 和 favicon 供 UI 展示。",
        payloadExample:
          '[{ "index": 0, "title": "Feed", "url": "https://example.com/feed", "favicon": "…" }]',
        dataDetailId: "data-tab-descriptor",
        sourceIds: ["src-server-tabs", "src-tabs-view", "src-automation-types"],
      },
      {
        id: "tabs-index-stale",
        from: "tabs-indexed",
        to: "tabs-requested",
        label: "索引失效后刷新",
        kind: "recovery",
        timing: "页面关闭、打开或重排后",
        window: [0.34, 0.52],
        explanation: "tab.index 只是数组位置；检测到无效索引后应重新获取页面，而不是重试旧位置。",
        payloadExample: '{ "tabIndex": 3, "pagesLength": 2, "action": "refetch" }',
        dataDetailId: "data-tab-descriptor",
        sourceIds: ["src-server-tabs", "src-execution", "src-tabs-view"],
      },
      {
        id: "tabs-resolve-pinned",
        from: "tabs-indexed",
        to: "tabs-pinned-resolved",
        label: "比较配置与实时 URL",
        kind: "normal",
        timing: "tabs 与 pinned 配置同时可用时",
        window: [0.42, 0.62],
        explanation: "先做精确 URL 匹配，再表达同域或关闭状态，让后续动作可解释。",
        payloadExample:
          '{ "id": "feed-monitor", "url": "https://example.com/feed", "derivedStatus": "domain" }',
        dataDetailId: "data-pinned-tab",
        sourceIds: ["src-tabs-view", "src-pinned", "src-automation-types"],
      },
      {
        id: "tabs-ensure",
        from: "tabs-pinned-resolved",
        to: "tabs-targeted",
        label: "复用、创建或导航",
        kind: "normal",
        timing: "用户启动 pinned tab",
        window: [0.62, 0.82],
        explanation: "exact 可激活现有页；domain/closed 可通过 ensure 落实为目标 URL 页面。",
        payloadExample: '{ "url": "https://example.com/feed", "index": 2, "action": "ensure" }',
        dataDetailId: "data-pinned-tab",
        sourceIds: ["src-tabs-view", "src-server-tabs", "src-pinned"],
      },
      {
        id: "tabs-persist-failed",
        from: "tabs-pinned-resolved",
        to: "tabs-pinned-resolved",
        label: "Pinned 写入失败",
        kind: "failure",
        timing: "保存 pinned_tabs.json 失败",
        window: [0.58, 0.72],
        explanation:
          "当前文件写错误可能被吞掉，UI 成功状态不等于配置已持久化；只能重新保存并核对。",
        payloadExample: '{ "saved": false, "uiMayAppearSuccessful": true }',
        dataDetailId: "data-pinned-tab",
        sourceIds: ["src-pinned", "src-tabs-view"],
      },
      {
        id: "tabs-handoff",
        from: "tabs-targeted",
        to: "tabs-ready",
        label: "构造定向运行",
        kind: "normal",
        timing: "页面确认后",
        window: [0.82, 1],
        explanation: "TabsView 将当前 index 和 URL 放进执行请求；服务端仍需再次验证索引和 URL。",
        payloadExample:
          '{ "filename": "04_youtube_feed.mjs", "tabIndex": "2", "targetUrl": "https://example.com/feed" }',
        dataDetailId: "data-execution-request",
        sourceIds: ["src-tabs-view", "src-execution"],
      },
    ],
  },
  {
    id: "flow-execution",
    number: "03",
    title: "执行与 Trace",
    summary:
      "EventSource 请求注册 runId，Runner 解析目标页和脚本，在 Fastify 进程内执行 AsyncFunction，并流式发送事件。",
    outcome:
      "正常返回、错误或协作式取消都会结束连接；只有经 sendLog 的事件可靠进入当前 Trace 写入路径。",
    accent: "#f0806c",
    primaryStageIds: [
      "execution-requested",
      "execution-registered",
      "execution-browser-ready",
      "execution-page-ready",
      "execution-prepared",
      "execution-running",
      "execution-terminal",
    ],
    primaryTransitionIds: [
      "execution-register",
      "execution-attach",
      "execution-resolve-page",
      "execution-prepare-source",
      "execution-invoke",
      "execution-stream-log",
      "execution-done",
    ],
    stages: [
      {
        id: "execution-requested",
        eyebrow: "INPUT",
        title: "打开 SSE",
        state: "执行 query 已到达服务端",
        progress: 0,
        participants: ["ScriptsView/TabsView", "Fastify"],
        before: "没有本次运行连接或服务端状态。",
        after: "服务端解析 filename、tabIndex、targetUrl、params 和可选 runId。",
        explanation: "默认 SSE message 连接既是命令入口也是结果通道，断线会参与取消语义。",
        outputs: ["ExecutionRequest", "SSE response"],
        sourceIds: ["src-scripts-view", "src-tabs-view", "src-execution"],
      },
      {
        id: "execution-registered",
        eyebrow: "CONTROL",
        title: "注册运行",
        state: "runId → AbortController",
        progress: 0.15,
        participants: ["Fastify", "activeScriptExecutions"],
        before: "请求尚无唯一运行控制记录。",
        after: "有效且未重复的 runId 关联取消信号。",
        explanation: "注册表防止同一 runId 并发复用，并让 cancel API 与连接关闭找到同一个控制器。",
        outputs: ["runId", "AbortSignal", "disconnect handler"],
        sourceIds: ["src-execution", "src-cancel"],
      },
      {
        id: "execution-browser-ready",
        eyebrow: "BOUNDARY",
        title: "确认浏览器",
        state: "Stagehand context 可用",
        progress: 0.3,
        participants: ["Fastify", "Stagehand", "Chrome"],
        before: "运行已注册，但尚无浏览器能力。",
        after: "可以枚举当前 pages；失败则直接终止。",
        explanation: "把外部浏览器可用性作为显式关卡，避免在无 Page 的情况下加载用户脚本。",
        outputs: ["Stagehand instance", "pages snapshot"],
        sourceIds: ["src-execution", "src-server-tabs"],
      },
      {
        id: "execution-page-ready",
        eyebrow: "TARGET",
        title: "解析并校准 Page",
        state: "targetPage 已选择",
        progress: 0.43,
        participants: ["Runner", "Stagehand Page", "Pinned config（可选）"],
        before: "只有瞬时 tabIndex 和可选目标 URL。",
        after: "索引有效，并在需要时尝试导航到 expectedUrl。",
        explanation: "再次验证位置和 URL，缩小用户选中页面到真正运行之间的竞态影响。",
        outputs: ["targetPage", "effective targetUrl"],
        sourceIds: ["src-execution", "src-pinned", "src-server-tabs"],
      },
      {
        id: "execution-prepared",
        eyebrow: "COMPILE",
        title: "读取并转译",
        state: "AsyncFunction body 已准备",
        progress: 0.58,
        participants: ["Runner", "Script FS", "Transpiler"],
        before: "目标页已确定，但磁盘源码尚未成为可调用函数体。",
        after: "import/type/interface/default wrapper 被处理，得到运行代码。",
        explanation: "Runner 适配项目约定的默认导出脚本；正则剥离并不等同完整模块系统。",
        outputs: ["transpiled codeBody"],
        sourceIds: ["src-execution", "src-server-scripts"],
      },
      {
        id: "execution-running",
        eyebrow: "SIDE EFFECT",
        title: "同进程执行",
        state: "AsyncFunction 正在运行",
        progress: 0.72,
        participants: ["用户脚本", "Fastify event loop", "Chrome", "SQLite"],
        before: "代码和能力已准备，但尚未执行用户逻辑。",
        after: "页面、网络或数据库可能已产生副作用，并持续发送 log/frame。",
        explanation:
          "脚本获得 page、stagehand、db、params、signal 和 fetch；它不是沙箱，且同步阻塞无法被强制抢占。",
        outputs: ["页面副作用", "SQLite 副作用", "SSE log/frame", "trace.json / JPEG"],
        sourceIds: ["src-execution", "src-cancel", "src-trace", "src-db-helper"],
      },
      {
        id: "execution-terminal",
        eyebrow: "TERMINAL",
        title: "结束并清理",
        state: "done / error / cancelled",
        progress: 1,
        participants: ["Runner", "SSE client", "Trace FS"],
        before: "函数仍在运行或正在响应取消。",
        after: "响应关闭，控制表移除 runId；不会留下可恢复任务。",
        explanation:
          "终态结束本次连接。done/error 通常只经 sendEvent，当前 Trace 不一定记录最终结论。",
        outputs: ["终态 SSE event", "partial or complete trace", "registry cleanup"],
        sourceIds: ["src-execution", "src-cancel", "src-trace", "src-automation-types"],
      },
    ],
    transitions: [
      {
        id: "execution-register",
        from: "execution-requested",
        to: "execution-registered",
        label: "验证并注册 runId",
        kind: "normal",
        timing: "SSE headers 设置后",
        window: [0, 0.16],
        explanation: "服务端生成或验证 runId，拒绝非法/重复值，并把 AbortController 放入内存表。",
        payloadExample:
          '{ "runId": "run_1760000000000_550e8400-e29b-41d4-a716-446655440000", "signal.aborted": false }',
        dataDetailId: "data-run-control",
        sourceIds: ["src-execution", "src-cancel"],
      },
      {
        id: "execution-preflight-error",
        from: "execution-requested",
        to: "execution-terminal",
        label: "请求预检失败",
        kind: "failure",
        timing: "runId 非法、重复或基础输入无效",
        window: [0.05, 0.2],
        explanation: "服务端发送可能缺少 runId/time 的 error 并关闭连接；此时可能没有 Trace 目录。",
        payloadExample: '{ "type": "error", "message": "无效的脚本运行 ID。" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution"],
      },
      {
        id: "execution-attach",
        from: "execution-registered",
        to: "execution-browser-ready",
        label: "确保 Stagehand",
        kind: "normal",
        timing: "控制记录建立后",
        window: [0.16, 0.31],
        explanation: "Runner 在加载脚本前确认 Chrome 可控，避免产生无法执行的半成品上下文。",
        payloadExample: '{ "type": "browser-ready", "pages": 4 }',
        dataDetailId: "data-runtime-context",
        sourceIds: ["src-execution", "src-server-tabs"],
      },
      {
        id: "execution-browser-error",
        from: "execution-registered",
        to: "execution-terminal",
        label: "浏览器连接失败",
        kind: "failure",
        timing: "ensureStagehand 抛错",
        window: [0.19, 0.33],
        explanation: "发送 error 后清理运行；恢复依赖外部 Chrome/CDP 就绪后创建一个新 run。",
        payloadExample: '{ "type": "error", "message": "Stagehand 未连接到 Chrome 浏览器。" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution", "src-server-tabs"],
      },
      {
        id: "execution-resolve-page",
        from: "execution-browser-ready",
        to: "execution-page-ready",
        label: "验证索引与 URL",
        kind: "normal",
        timing: "取得 pages 快照后",
        window: [0.31, 0.45],
        explanation:
          "tabIndex 被转换为 number 并检查边界，targetUrl 或 pinned URL 可触发执行前导航。",
        payloadExample:
          '{ "tabIndex": 2, "targetUrl": "https://example.com/feed", "action": "goto-if-needed" }',
        dataDetailId: "data-tab-descriptor",
        sourceIds: ["src-execution", "src-pinned", "src-server-tabs"],
      },
      {
        id: "execution-page-error",
        from: "execution-browser-ready",
        to: "execution-terminal",
        label: "目标索引失效",
        kind: "failure",
        timing: "index 越界或非数字",
        window: [0.34, 0.48],
        explanation: "运行停止而不是选择其他页面；用户必须刷新 tabs 并重新启动。",
        payloadExample:
          '{ "type": "error", "message": "目标 Tab 序号 #3 无效或超出了打开的页签数量 (2)" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution", "src-tabs-view"],
      },
      {
        id: "execution-prepare-source",
        from: "execution-page-ready",
        to: "execution-prepared",
        label: "读取、剥离、转译",
        kind: "normal",
        timing: "目标页校准后",
        window: [0.45, 0.6],
        explanation: "磁盘源码被处理为 AsyncFunction body；复杂模块结构可能超出正则剥离能力。",
        payloadExample:
          '{ "filename": "04_youtube_feed.mjs", "transformation": ["strip imports", "strip types", "safeTranspile"] }',
        dataDetailId: "data-script-source",
        sourceIds: ["src-execution", "src-server-scripts"],
      },
      {
        id: "execution-invoke",
        from: "execution-prepared",
        to: "execution-running",
        label: "注入能力并调用",
        kind: "normal",
        timing: "codeBody 可执行后",
        window: [0.6, 0.74],
        explanation:
          "AsyncFunction 获得可中止 page/fetch 和其他高权限能力，并与 Fastify 共用事件循环。",
        payloadExample:
          '{ "injected": ["page", "stagehand", "log", "console", "db", "params", "signal", "fetch"] }',
        dataDetailId: "data-runtime-context",
        sourceIds: ["src-execution", "src-cancel", "src-db-helper"],
      },
      {
        id: "execution-stream-log",
        from: "execution-running",
        to: "execution-running",
        label: "发送 log / frame",
        kind: "normal",
        timing: "脚本调用 log(message) 时",
        window: [0.72, 0.9],
        explanation: "文字先立即发送；截图异步按时间或动作关键词采集，frame 可能复用最近图片。",
        payloadExample:
          '{ "type": "frame", "runId": "run_…", "step": 3, "message": "滚动页面", "frameUrl": "http://localhost:3001/api/traces/run_…/frame/frame_3.jpg" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution", "src-trace"],
      },
      {
        id: "execution-persist-trace",
        from: "execution-running",
        to: "execution-running",
        label: "重写 Trace",
        kind: "normal",
        timing: "每次 sendLog 截图尝试后",
        window: [0.76, 0.92],
        explanation:
          "trace.json 汇总当前 logs/frames；JSON 与 JPEG 非原子写入，进程退出可能留下部分产物。",
        payloadExample:
          '{ "runId": "run_…", "timestamp": "2026/8/12 10:30:08", "totalFrames": 3, "totalLogs": 5 }',
        dataDetailId: "data-trace-artifact",
        sourceIds: ["src-trace", "src-execution"],
      },
      {
        id: "execution-done",
        from: "execution-running",
        to: "execution-terminal",
        label: "正常完成",
        kind: "normal",
        timing: "AsyncFunction 正常返回",
        window: [0.9, 1],
        explanation:
          "done 通过 sendEvent 发送并关闭连接，但通常不追加到 traceLogs，因此回放不保证拥有成功终态。",
        payloadExample:
          '{ "type": "done", "runId": "run_…", "time": "10:30:12", "message": "脚本全部执行完毕" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution", "src-trace", "src-automation-types"],
      },
      {
        id: "execution-runtime-error",
        from: "execution-running",
        to: "execution-terminal",
        label: "运行异常",
        kind: "failure",
        timing: "用户脚本或自动化调用抛错",
        window: [0.8, 1],
        explanation:
          "error 发送到 UI 后清理控制记录；与 done 相同，当前通常不进入持久 Trace 日志。",
        payloadExample:
          '{ "type": "error", "runId": "run_…", "message": "脚本执行异常中断: timeout" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-execution", "src-trace"],
      },
      {
        id: "execution-cancel",
        from: "execution-running",
        to: "execution-terminal",
        label: "协作式取消",
        kind: "alternate",
        timing: "cancel API 或 SSE 连接关闭",
        window: [0.78, 0.98],
        explanation:
          "AbortController 通知代理和脚本；同步循环或进行中的同步 SQLite 无法被抢占。cancelled 经 sendLog 会进入 Trace。",
        payloadExample: '{ "type": "cancelled", "runId": "run_…", "message": "脚本已中止。" }',
        dataDetailId: "data-sse-event",
        sourceIds: ["src-cancel", "src-execution", "src-trace", "src-automation-types"],
      },
    ],
  },
  {
    id: "flow-database",
    number: "04",
    title: "SQLite 数据",
    summary:
      "自动化脚本通过 db helper 写入动态表，DatabaseView 再经 Fastify API 枚举、分页、删除和导出。",
    outcome:
      "数据最终落入 cbg_data.db；标识符拼接、主键推测和当前页导出限制决定了管理操作的安全边界。",
    accent: "#9d8ad8",
    primaryStageIds: [
      "database-produced",
      "database-requested",
      "database-schema",
      "database-executed",
      "database-returned",
      "database-presented",
    ],
    primaryTransitionIds: [
      "database-write",
      "database-list",
      "database-build-query",
      "database-query",
      "database-render",
    ],
    stages: [
      {
        id: "database-produced",
        eyebrow: "PRODUCER",
        title: "脚本产生数据",
        state: "动态表或行可能写入",
        progress: 0,
        participants: ["用户脚本", "db helper", "SQLite"],
        before: "采集结果只在脚本内存中。",
        after: "createTable/upsert/query 可对 cbg_data.db 产生副作用。",
        explanation: "数据库的业务 schema 不在迁移文件中，而是由自动化脚本按运行需要动态形成。",
        outputs: ["SQLite table", "persisted rows"],
        sourceIds: ["src-db-helper", "src-youtube-script"],
      },
      {
        id: "database-requested",
        eyebrow: "DISCOVER",
        title: "请求表目录",
        state: "DatabaseView 获取表与数量",
        progress: 0.2,
        participants: ["DatabaseView", "DB routes", "SQLite"],
        before: "UI 不知道当前数据库有哪些用户表。",
        after: "可选择表并展示行数等指标。",
        explanation: "先从 SQLite 实际状态发现动态 schema，而不是依赖静态前端配置。",
        outputs: ["DbTableInfo[]"],
        sourceIds: ["src-db-view", "src-db-routes", "src-automation-types"],
      },
      {
        id: "database-schema",
        eyebrow: "BOUNDARY",
        title: "解析表与列",
        state: "SQL identifier 已进入请求",
        progress: 0.4,
        participants: ["DatabaseView", "Fastify DB routes"],
        before: "只有用户选择的表、分页或删除意图。",
        after: "服务端将表名/列名用于构造 SQL。",
        explanation: "这是关键安全边界：值参数化不能保护 identifier，必须用实际 schema allowlist。",
        outputs: ["table identifier", "column identifiers", "bound values"],
        sourceIds: ["src-db-routes", "src-db-view"],
      },
      {
        id: "database-executed",
        eyebrow: "SQL",
        title: "执行查询或变更",
        state: "SQLite statement 完成",
        progress: 0.63,
        participants: ["Fastify", "db helper", "SQLite"],
        before: "SQL 和参数已构造但尚无数据库结果。",
        after: "得到行集/计数，或表内数据发生删除、清空、replace。",
        explanation: "读取和变更共用本地 SQLite；INSERT OR REPLACE 可能替换整行而非字段合并。",
        outputs: ["rows", "total", "mutation count", "SQLite side effect"],
        sourceIds: ["src-db-routes", "src-db-helper"],
      },
      {
        id: "database-returned",
        eyebrow: "RESPONSE",
        title: "返回分页结果",
        state: "API 响应进入前端",
        progress: 0.82,
        participants: ["DB routes", "DatabaseView"],
        before: "数据仍是 SQLite 查询结果。",
        after: "UI 拥有当前页 rows、total 和字段信息。",
        explanation: "分页限制浏览器内存和渲染成本，但当前已加载页不代表完整表。",
        outputs: ["DbRow[]", "pagination metadata"],
        sourceIds: ["src-db-routes", "src-db-view", "src-automation-types"],
      },
      {
        id: "database-presented",
        eyebrow: "DERIVED VIEW",
        title: "展示或导出",
        state: "表格、指标或文件已生成",
        progress: 1,
        participants: ["DatabaseView", "用户"],
        before: "只有当前分页响应。",
        after: "用户看到表格，或导出当前已加载行。",
        explanation: "展示是查询结果的派生视图；导出必须明确范围，避免把当前页误称整表。",
        outputs: ["Data grid", "metrics", "current-page export"],
        sourceIds: ["src-db-view"],
      },
    ],
    transitions: [
      {
        id: "database-write",
        from: "database-produced",
        to: "database-requested",
        label: "脚本写入 SQLite",
        kind: "normal",
        timing: "自动化脚本调用 db helper",
        window: [0, 0.22],
        explanation: "脚本创建表并写入采集行，随后 DatabaseView 才能从真实数据库发现它们。",
        payloadExample:
          '{ "table": "youtube_videos", "values": { "video_id": "abc123", "title": "示例标题" } }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-helper", "src-youtube-script"],
      },
      {
        id: "database-upsert-replace",
        from: "database-produced",
        to: "database-produced",
        label: "INSERT OR REPLACE",
        kind: "alternate",
        timing: "db.upsert 遇到冲突键",
        window: [0.05, 0.2],
        explanation: "名称是 upsert，但实现会 replace 整行；遗漏列可能回落默认值或丢失旧内容。",
        payloadExample: '{ "operation": "INSERT OR REPLACE", "conflictKey": "video_id" }',
        dataDetailId: "data-db-result",
        sourceIds: ["src-db-helper"],
      },
      {
        id: "database-write-flag-mismatch",
        from: "database-produced",
        to: "database-produced",
        label: "saveToDb=false 仍写入",
        kind: "failure",
        timing: "运行 04_youtube_feed.mjs 时",
        window: [0.08, 0.24],
        explanation: "示例脚本当前无条件调用 upsert，参数意图与真实副作用不一致。",
        payloadExample: '{ "params.saveToDb": false, "observedSideEffect": "db.upsert called" }',
        dataDetailId: "data-db-result",
        sourceIds: ["src-youtube-script", "src-db-helper"],
      },
      {
        id: "database-list",
        from: "database-requested",
        to: "database-schema",
        label: "选择动态表",
        kind: "normal",
        timing: "进入数据库页或刷新",
        window: [0.22, 0.42],
        explanation: "UI 从实际表目录中选择目标，并把表名带入分页请求。",
        payloadExample: '{ "table": "youtube_videos", "page": 1, "pageSize": 50 }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-view", "src-db-routes"],
      },
      {
        id: "database-build-query",
        from: "database-schema",
        to: "database-executed",
        label: "构造并执行 SQL",
        kind: "normal",
        timing: "表和分页参数到达服务端",
        window: [0.42, 0.66],
        explanation:
          "服务端执行 count 和分页 select；当前部分标识符直接拼接，是必须优先收紧的边界。",
        payloadExample:
          '{ "sqlShape": "SELECT * FROM <table> LIMIT ? OFFSET ?", "boundValues": [50, 0] }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-routes"],
      },
      {
        id: "database-delete-row",
        from: "database-schema",
        to: "database-executed",
        label: "按推测主键删除",
        kind: "alternate",
        timing: "用户确认删除一行",
        window: [0.48, 0.69],
        explanation:
          "前端推测 primaryKeyCol 并提交值；复合键、错误候选或 falsy 值可能导致失败或删除范围错误。",
        payloadExample: '{ "table": "youtube_videos", "column": "video_id", "value": "abc123" }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-view", "src-db-routes"],
      },
      {
        id: "database-clear",
        from: "database-schema",
        to: "database-executed",
        label: "清空整表",
        kind: "alternate",
        timing: "用户确认 clear",
        window: [0.5, 0.7],
        explanation: "这是不可逆的表级副作用；表名必须由 schema 校验，UI 需要保持明确确认。",
        payloadExample: '{ "table": "youtube_videos", "operation": "clear" }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-view", "src-db-routes"],
      },
      {
        id: "database-identifier-risk",
        from: "database-schema",
        to: "database-schema",
        label: "Identifier 未白名单",
        kind: "failure",
        timing: "表名或列名进入 SQL 拼接时",
        window: [0.4, 0.61],
        explanation:
          "普通参数绑定只保护值；恢复方案是从 sqlite schema 解析 allowlist 并安全引用 identifier。",
        payloadExample:
          '{ "risk": "untrusted SQL identifier", "requiredRecovery": "schema allowlist" }',
        dataDetailId: "data-db-operation",
        sourceIds: ["src-db-routes"],
      },
      {
        id: "database-query",
        from: "database-executed",
        to: "database-returned",
        label: "序列化行与分页",
        kind: "normal",
        timing: "SQLite statement 完成后",
        window: [0.66, 0.84],
        explanation: "行对象和总数返回前端，为数据网格和分页器提供同一份查询窗口。",
        payloadExample: '{ "rows": [{ "video_id": "abc123" }], "total": 248, "page": 1 }',
        dataDetailId: "data-db-result",
        sourceIds: ["src-db-routes", "src-db-view"],
      },
      {
        id: "database-render",
        from: "database-returned",
        to: "database-presented",
        label: "渲染当前页",
        kind: "normal",
        timing: "API 响应成功后",
        window: [0.84, 1],
        explanation: "网格、指标、分页和导出都基于当前已加载数据；导出不能声称覆盖整张表。",
        payloadExample: '{ "visibleRows": 50, "totalRows": 248, "exportScope": "loaded-page" }',
        dataDetailId: "data-db-result",
        sourceIds: ["src-db-view"],
      },
    ],
  },
];
